import { NextAuthOptions } from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';
import bcrypt from 'bcryptjs';
import User from "@/models/User";
import dbConnect from "@/lib/dbConnect";

export const authOptions: NextAuthOptions = {
    providers: [
        CredentialsProvider({
            name: 'Credentials',
            credentials: {
                email: { label: "Email", type: "text" },
                password: {  label: "Password", type: "password" }
            },
            async authorize(credentials) {
                await dbConnect();
                if (!credentials) {
                  throw new Error("Invalid credentials");
                }
                const user = await User.findOne({ email: credentials.email });

                if (!user) {
                  throw new Error("No user found with this email");
                }

                let isValid = false;

                if (user.passwordHash) {
                  // User has a hashed password, compare it
                  isValid = await bcrypt.compare(credentials.password, user.passwordHash);
                } else if (user.password) {
                  // This is a legacy user with a plain-text password.
                  // This is a temporary measure for migration.
                  // IMPORTANT: This block should be removed after all users have migrated.
                  isValid = user.password === credentials.password;
                  if (isValid) {
                    // Migrate to hashed password
                    const salt = await bcrypt.genSalt(10);
                    user.passwordHash = await bcrypt.hash(user.password, salt);
                    user.password = undefined; // Remove plain-text password
                    await user.save();
                  }
                } else {
                  // No password or passwordHash found.
                  // This can happen if the user signed up with an OAuth provider.
                  throw new Error("Please sign in using your social account or contact support.");
                }

                if (!isValid) {
                  throw new Error("Incorrect password");
                }

                if (!user.verified) {
                  throw new Error("Your account is pending verification by an administrator.");
                }

                return {
                  id: user._id.toString(),
                  _id: user._id.toString(),
                  email: user.email,
                  fullName: user.fullName,
                  role: user.role,
                  organizationId: user.organizationId.toString(),
                  image: user.image, 
                  token: "placeholder", // This satisfies the type, but the real token is generated by NextAuth
                };
              }
        })
    ],
    callbacks: {
        async jwt({ token, user }) {
            if (user) {
                await dbConnect();
                const dbUser = await User.findById(user.id);
                if (dbUser) {
                    token.id = dbUser._id.toString();
                    token._id = dbUser._id.toString();
                    token.role = dbUser.role;
                    token.organizationId = dbUser.organizationId.toString();
                    token.image = dbUser.image;
                }
            }
            return token;
        },
        async session({ session, token }) {
            if (session.user) {
                session.user.id = token.id as string;
                session.user._id = token._id as string;
                session.user.role = token.role as string;
                session.user.organizationId = token.organizationId as string;
                session.user.image = token.image as string;
            }
            return session;
        }
    },
    session: {
        strategy: "jwt",
    },
    pages: {
        signIn: '/login',
    },
};