import { NextAuthOptions } from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';
import bcrypt from 'bcryptjs';
import User from "@/models/User";
import dbConnect from "@/lib/dbConnect";

export const authOptions: NextAuthOptions = {
    providers: [
        CredentialsProvider({
            name: 'Credentials',
            credentials: {
                email: { label: "Email", type: "text" },
                password: {  label: "Password", type: "password" }
            },
            async authorize(credentials) {
                await dbConnect();
                if (!credentials) {
                  throw new Error("Invalid credentials");
                }
                const user = await User.findOne({ email: credentials.email });

                if (!user) {
                  throw new Error("No user found with this email");
                }

                if (!user.passwordHash) {
                  // This case can happen if the user signed up with an OAuth provider
                  // and is now trying to sign in with credentials.
                  throw new Error("Please sign in using your social account");
                }

                const isValid = await bcrypt.compare(credentials.password, user.passwordHash);

                if (!isValid) {
                  throw new Error("Incorrect password");
                }

                if (!user.verified) {
                  throw new Error("Your account is pending verification by an administrator.");
                }

                return {
                  id: user._id.toString(),
                  _id: user._id.toString(),
                  email: user.email,
                  fullName: user.fullName,
                  role: user.role,
                  organizationId: user.organizationId.toString(),
                  token: "placeholder", // This satisfies the type, but the real token is generated by NextAuth
                };
              }
        })
    ],
    callbacks: {
        async jwt({ token, user }) {
            if (user) {
                token.id = user.id;
                token.role = user.role;
                token.organizationId = user.organizationId;
            }
            return token;
        },
        async session({ session, token }) {
            if (session.user) {
                session.user.id = token.id as string;
                session.user.role = token.role as string;
                session.user.organizationId = token.organizationId as string;
            }
            return session;
        }
    },
    session: {
        strategy: "jwt",
    },
    pages: {
        signIn: '/login',
    },
};